### ISSUE TITLE
Handle search terms with spaces better

### ISSUE THREAD

**Issue by drzax** [jesserobertson/databot#1]
databot doesn't to a great job of dealing with spaces in search terms. 

They are (probably sensibly) converted to '+' for performing the query, however the resulting more link links to a search without the plus (meaning it has different results to the ones reported by databot in slack).

e.g: 

> Simon Elvery [2:23 PM] 
> databot find daylight savings
> 
> databotBOT [2:23 PM] 
> Thanks @simon. I found 30 results for daylight+savings at data.gov.au, here's the top result:
> There's no description for this file (it's in an unknown format). Get it here.
> Want more? Check out this link.

The more link results in a search for 'daylight savings' which had just a single result at the time of searching, while slack bot is reporting the 30 results from a search for 'daylight+savings'.

**Comment by jesserobertson** [comment]
oh only just noticed this - will have a look - thanks @drzax

**Comment by jesserobertson** [comment]
ok so after forgetting about this I found out that this is an issue with the way the CKAN UI interprets search terms - '+' gets mapped to spaces when the URL is resolved.

Workaround is to specify the query with %2B instead and now things work.
